// <auto-generated />
using System;
using CeremonyMonitorApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CeremonyMonitorApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260731013635_AddCeremony")]
    partial class AddCeremony
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CeremonyMonitorApp.Models.Ceremony", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Ceremonies");
                });

            modelBuilder.Entity("CeremonyMonitorApp.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Air Conditioner"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Refrigeration"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Home Appliances"
                        },
                        new
                        {
                            Id = 4,
                            Name = "TV Assembly"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Battery Pack"
                        });
                });

            modelBuilder.Entity("CeremonyMonitorApp.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("ExternalID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            FullName = "Takeshi Sato",
                            Position = "Production Manager"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            FullName = "Maya Nakajima",
                            Position = "Executive Assistant"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 1,
                            FullName = "Ryu Watanabe",
                            Position = "Internal Comms Specialist"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 2,
                            FullName = "Dewi Anjani",
                            Position = "HR Coordinator"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 2,
                            FullName = "Hiroshi Kato",
                            Position = "Line Lead"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 3,
                            FullName = "Airi Kobayashi",
                            Position = "Quality Inspector"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 3,
                            FullName = "Budi Santoso",
                            Position = "Shift Supervisor"
                        });
                });

            modelBuilder.Entity("CeremonyMonitorApp.Models.Ceremony", b =>
                {
                    b.HasOne("CeremonyMonitorApp.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CeremonyMonitorApp.Models.Employee", b =>
                {
                    b.HasOne("CeremonyMonitorApp.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });
#pragma warning restore 612, 618
        }
    }
}
