// <auto-generated />
using System;
using CeremonyMonitorApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CeremonyMonitorApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260731064258_AddSpeech")]
    partial class AddSpeech
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CeremonyMonitorApp.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("CeremonyMonitorApp.Models.Awardee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CeremonyId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("HrAdminNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HrManagerNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NominatingDepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReviewedByHrAdminId")
                        .HasColumnType("int");

                    b.Property<int?>("ReviewedByHrManagerId")
                        .HasColumnType("int");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubmittedById")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CeremonyId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("NominatingDepartmentId");

                    b.HasIndex("ReviewedByHrAdminId");

                    b.HasIndex("ReviewedByHrManagerId");

                    b.HasIndex("SubmittedById");

                    b.ToTable("Awardees");
                });

            modelBuilder.Entity("CeremonyMonitorApp.Models.Ceremony", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Ceremonies");
                });

            modelBuilder.Entity("CeremonyMonitorApp.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Air Conditioner"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Refrigeration"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Home Appliances"
                        },
                        new
                        {
                            Id = 4,
                            Name = "TV Assembly"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Battery Pack"
                        });
                });

            modelBuilder.Entity("CeremonyMonitorApp.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("ExternalID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            FullName = "Takeshi Sato",
                            Position = "Production Manager"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            FullName = "Maya Nakajima",
                            Position = "Executive Assistant"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 1,
                            FullName = "Ryu Watanabe",
                            Position = "Internal Comms Specialist"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 2,
                            FullName = "Dewi Anjani",
                            Position = "HR Coordinator"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 2,
                            FullName = "Hiroshi Kato",
                            Position = "Line Lead"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 3,
                            FullName = "Airi Kobayashi",
                            Position = "Quality Inspector"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 3,
                            FullName = "Budi Santoso",
                            Position = "Shift Supervisor"
                        });
                });

            modelBuilder.Entity("CeremonyMonitorApp.Models.RoleAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CeremonyId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("RoleType")
                        .HasColumnType("int");

                    b.Property<bool>("Submitted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("CeremonyId", "EmployeeId")
                        .IsUnique();

                    b.ToTable("RoleAssignments");
                });

            modelBuilder.Entity("CeremonyMonitorApp.Models.Speech", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttributedToId")
                        .HasColumnType("int");

                    b.Property<int>("CeremonyId")
                        .HasColumnType("int");

                    b.Property<int>("InputById")
                        .HasColumnType("int");

                    b.Property<string>("TextIndonesia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextJapanaese")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AttributedToId");

                    b.HasIndex("CeremonyId");

                    b.HasIndex("InputById");

                    b.ToTable("Speeches");
                });

            modelBuilder.Entity("CeremonyMonitorApp.Models.AppUser", b =>
                {
                    b.HasOne("CeremonyMonitorApp.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CeremonyMonitorApp.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("CeremonyMonitorApp.Models.Awardee", b =>
                {
                    b.HasOne("CeremonyMonitorApp.Models.Ceremony", "Ceremony")
                        .WithMany()
                        .HasForeignKey("CeremonyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CeremonyMonitorApp.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CeremonyMonitorApp.Models.Department", "NominatingDepartment")
                        .WithMany()
                        .HasForeignKey("NominatingDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CeremonyMonitorApp.Models.AppUser", "ReviewedByHrAdmin")
                        .WithMany()
                        .HasForeignKey("ReviewedByHrAdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CeremonyMonitorApp.Models.AppUser", "ReviewedByHrManager")
                        .WithMany()
                        .HasForeignKey("ReviewedByHrManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CeremonyMonitorApp.Models.AppUser", "SubmittedBy")
                        .WithMany()
                        .HasForeignKey("SubmittedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ceremony");

                    b.Navigation("Employee");

                    b.Navigation("NominatingDepartment");

                    b.Navigation("ReviewedByHrAdmin");

                    b.Navigation("ReviewedByHrManager");

                    b.Navigation("SubmittedBy");
                });

            modelBuilder.Entity("CeremonyMonitorApp.Models.Ceremony", b =>
                {
                    b.HasOne("CeremonyMonitorApp.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CeremonyMonitorApp.Models.Employee", b =>
                {
                    b.HasOne("CeremonyMonitorApp.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CeremonyMonitorApp.Models.RoleAssignment", b =>
                {
                    b.HasOne("CeremonyMonitorApp.Models.Ceremony", "Ceremony")
                        .WithMany()
                        .HasForeignKey("CeremonyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CeremonyMonitorApp.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ceremony");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("CeremonyMonitorApp.Models.Speech", b =>
                {
                    b.HasOne("CeremonyMonitorApp.Models.Employee", "AttributedTo")
                        .WithMany()
                        .HasForeignKey("AttributedToId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CeremonyMonitorApp.Models.Ceremony", "Ceremony")
                        .WithMany()
                        .HasForeignKey("CeremonyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CeremonyMonitorApp.Models.AppUser", "InputBy")
                        .WithMany()
                        .HasForeignKey("InputById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AttributedTo");

                    b.Navigation("Ceremony");

                    b.Navigation("InputBy");
                });
#pragma warning restore 612, 618
        }
    }
}
